[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.railway"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
SELF_HOSTED = "true"
ENABLE_TELEMETRY = "false"
ENABLE_ANALYTICS = "false"
ALLOW_REGISTRATION = "true"
REMINDER_CRON_ENABLED = "true"
REMINDER_CHECK_INTERVAL = "0 9 * * *"
ENABLE_EMAIL_REMINDERS = "true"
RAILWAY_DEPLOYMENT = "true"